/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-30-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class MyTriggerTest {
    @isTest static void EditLastName(){
      /*  Account acct = new Account(Name='SFDC Account');
        insert acct;
    
    Test.startTest();
        // Add a contact to this account.
        Contact con = new Contact(
            FirstName='Joe',
            LastName='Smith',
            Phone='415.555.1212',
            AccountId=acct.id);
        insert con;
    Test.stopTest();
        
    */
    }
}