/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-30-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private  class NewClassTest {
  @isTest static void TestAccount() {
    /*Account acct = new Account(Name='Account Test');
   Test.startTest();
    insert(acct); 
    Test.stopTest();
    }*/
  }
}